[package]
name = "rgbpp-node"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "rgbpp-indexer"
path = "src/main.rs"

[dependencies]
rgbpp-types = { workspace = true }
rgbpp-ckb = { workspace = true }
rgbpp-btc = { workspace = true }
rgbpp-store = { workspace = true }
rgbpp-indexer = { workspace = true }
rgbpp-api = { workspace = true }

anyhow = { workspace = true }
clap = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
toml = { workspace = true }
